### ISSUE TITLE
Not showing recent added profile such as Priscilla as she created their same day and time as I did?

### ISSUE THREAD

**Issue by Aquahoya** [PhitNest/phitnest#115]
This is "WEB VERSION"

**Comment by JohnSiegel** [comment]
Kevin most likely made an account before Priscilla, then opened the explore page before Priscilla completed her account. The explore page is loaded one time upon logging into the app, so Kevin would have had to restart the app in order to see Priscilla's newly created account on the explore page. **The app does not have an capability to refresh the explore page once it has been initially loaded** (future feature?)

To confirm that this ticket can be closed:

1. Have an account
2. Log out of your existing account
3. Create a new account
4. Logout of the new account
5. Log back into the original account and check explore page, you should see the second account present. If the second account is not present, there is a bug.

**Comment by CaglarKullu** [comment]
![image](https://github.com/PhitNest/phitnest/assets/97615706/98b609b7-9542-4d61-9725-04961619d5a0)
Followed the steps and can see the second account
